#!/bin/python3
import math
import os
import random
import re
import sys

#
# Complete the 'rotateLeft' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER d
#  2. INTEGER_ARRAY arr
#

def rotateLeft(d, arr, n):
    print ("array "+str(arr))
    num=0
    a1 = arr[num] # [>1<,2,3,4,5]
    a2 = arr[num+1] # [1,>2<,3,4,5]
    for i in range(d):
            print("num " + str(num))
            arr[num+1] = a1 #[1,1(2),3,4,5]
            a1 = a2
            if n == 2:
                arr[num] = a1
                print ("array "+str(arr))
                break
            print ("array "+str(arr))
            print ("a1 and a2 "+str(a1)+" "+str(a2))
            if num+2 != n:
                a2 = arr[num+2]
            else:
                print("max event")
                arr[0] = a1
                print ("array "+str(arr))
                break
            num = num+1
            if num == n:
                arr[0] = arr[num-1]
                
                
    return(arr)
                
    return(arr)        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    d = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = rotateLeft(d, arr, n)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
